services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: >
      mlflow server
      --host 0.0.0.0
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlruns
      --serve-artifacts
      --allowed-hosts=*
    environment:
      - MLFLOW_UI_TIMEOUT=600
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - mlflowdb:/mlflow

  api:
    build: .
    image: rakuten-mlops:latest
    container_name: rakuten_api
    ports: ["8000:8000"]
    environment:
      - API_USER=${API_USER:-admin}
      - API_PASS=${API_PASS:-changeme}
      - MLFLOW_URI=http://mlflow:5000
      - DB_PATH=/workspace/data/processed/rakuten.db
      - EXPERIMENT=rakuten_text_baseline
      - REGISTER_NAME=rakuten_clf
    depends_on: [mlflow]
    volumes:
      - ./data:/workspace/data
      - ./mlruns:/workspace/mlruns

  streamlit:
    build: ./streamlit
    environment:
      - API_URL=http://api:8000
    depends_on: [api]
    ports: ["8501:8501"]

volumes:
  mlflowdb: {}
