name: ci
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: flake8
      - name: Tests
        run: |
          export PYTHONPATH=.
          pytest -q
      - name: Docker build (api/trainer)
        run: |
          docker build -t rakuten-mlops:ci .
