name: release

on:
  push:
    tags:
      - 'v*.*.*'   # e.g. v1.0.0

jobs:
  release-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 httpx

      - name: Lint
        run: flake8

      - name: Tests
        run: |
          export PYTHONPATH=.
          pytest -q

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/rakuten-mlops
          docker build -t $IMAGE:${{ github.ref_name }} .
          docker tag $IMAGE:${{ github.ref_name }} $IMAGE:latest
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Push image
        run: |
          docker push $IMAGE:${{ github.ref_name }}
          docker push $IMAGE:latest
